<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class MarkAlphaAttendance extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:mark-alpha-attendance';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting auto-alpha check...');

        // 1. Get active sessions that have expired
        $expiredSessions = \App\Models\AttendanceSession::where('is_active', true)
            ->where('end_time', '<', \Carbon\Carbon::now())
            ->with(['timetableEntry.template' => function($q) {
                // Ensure we can access the class
                $q->with('class');
            }])
            ->get();

        $count = 0;

        foreach ($expiredSessions as $session) {
            $this->info("Processing session ID: {$session->id} (Token: {$session->token})");

            $timetableEntry = $session->timetableEntry;
            if (!$timetableEntry || !$timetableEntry->template || !$timetableEntry->template->class) {
                $this->warn("Skipping session {$session->id}: Incomplete relationship data.");
                continue;
            }

            $classroom = $timetableEntry->template->class;

            // 2. Get students in this class
            // Assuming ClassHistory tracks active students. We need the latest history or check a 'u_class_histories' table/view if complex.
            // For now, let's assume ClassHistory has 'is_active' or similar, OR we take the Latest.
            // Let's look at ClassHistory model... it links student_id and class_id.
            // We'll fetch all students currently assigned to this class.
            
            // NOTE: Adjust logic based on how you track "Current Class". 
            // Often it's: ClassHistory where class_id = X and (end_date is null OR academic_year = current)
            // Let's assume for now we get all students with a history in this class for the current academic year/semester if possible.
            // Simplified: All students whose LATEST history is this class.
            
            // Let's try a simpler approach if ClassHistory structure isn't fully known:
            // Get all students where their *current* class is this class.
            // Since we don't have full context on "Current", let's query ClassHistory.
            
            $studentsInClass = \App\Models\ClassHistory::where('class_id', $classroom->id)
                // ->where('is_active', true) // Uncomment if such flag exists
                ->with('student.user')
                ->get()
                ->pluck('student.user');

            foreach ($studentsInClass as $user) {
                if (!$user) continue;

                // 3. Check if they have attended TODAY (Daily Attendance Rule)
                $hasAttendedToday = \App\Models\AttendanceRecord::where('user_id', $user->id)
                    ->whereDate('scanned_at', \Carbon\Carbon::today())
                    ->exists();

                if (!$hasAttendedToday) {
                    // 4. Mark Alpha
                    \App\Models\AttendanceRecord::create([
                        'attendance_session_id' => $session->id,
                        'user_id' => $user->id,
                        'status' => 'alpa',
                        'scanned_at' => \Carbon\Carbon::now(),
                        'note' => 'Auto-generated by system (Alpha)',
                    ]);
                    $count++;
                }
            }

            // 5. Close Session
            $session->update(['is_active' => false]);
            $this->info("Closed session {$session->id}.");
        }

        $this->info("Marked {$count} students as Alpha.");
    }
}
